### ISSUE TITLE
About bias correction part

### ISSUE THREAD

**Issue by JasonSheng-atp** [raymondngiam/subpixel-edge-contour-in-opencv#1]
Hi, it is an excellent work! I find Steger did the bias correction part for asymmetrical line in the Section 5. Will you implement this part?

**Comment by raymondngiam** [comment]
No plan of implementing it as of now. Pull requests are welcomed though.

**Comment by JasonSheng-atp** [comment]
Thank you for response. I am also trying to implement this algorithm.
